### ISSUE TITLE
Document NNS usage with Wagmi/Viem

### ISSUE THREAD

**Issue by brunowowk** [nnsprotocol/nns-resolver-demo#1]
A lot of projects are migrating out of ethers to Wagmi/Viem. It's important to document how to use NNS with those

**Comment by apbigcod** [comment]
Hey @volkyeth thanks for the feedback!! We have now released [@nnsprotocol/resolver-wagmi](https://www.npmjs.com/package/@nnsprotocol/resolver-wagmi) for a very quick integration with Wagmi!
